name: Cypress Tests

on: [push]

jobs: 
  cypress-electron-tests:
    runs-on: ubunto-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4.2.1

      - name: Install dependencies
        run: npm install

      - name: Run E2E tests
        run: npx cypress run
